/**
 * Labels of the settable keys (Settings → General). They live next to the Settings chunk, not in
 * the initial dictionaries: only that page shows them, and the initial bundle has a size budget.
 * `tests/web-i18n.test.ts` fails when a settable key of the server has no label in a language.
 */
import type { Locale } from "../../i18n/index.ts";

export const SETTING_LABELS: Record<Locale, Record<string, string>> = {
  en: {
    "compaction.auto": "Compact the context automatically",
    "compaction.threshold": "Compaction threshold (fraction of the window)",
    "compaction.keepTurns": "Recent turns kept verbatim",
    "compaction.maxOutputTokens": "Summary length (tokens)",
    "context.claudeMdFallback": "Read CLAUDE.md when there is no AGENTS.md",
    "context.maxBytes": "Project instructions limit (bytes)",
    "limits.maxTurns": "Turns per run",
    "limits.maxOutputTokens": "Output tokens per turn",
    "limits.maxContextChars": "Context characters sent",
    "limits.timeoutMs": "Run time limit, active time (ms)",
    "limits.firstTokenTimeoutMs": "First-token timeout (ms)",
    "limits.firstTokenRetries": "Retries when the model stays silent",
    "limits.truncationRecoveries": "Recoveries from truncated output",
    "pluginHooks.timeoutMs": "Plugin hook timeout (ms)",
    "pluginHooks.disposeTimeoutMs": "Plugin shutdown timeout (ms)",
    "decisions.enabled": "Decision Intelligence",
    "decisions.provider": "Decision provider",
    "decisions.timeoutMs": "Decision timeout (ms)",
    "decisions.minConfidence": "Decision minimum confidence",
    "decisions.telemetry": "Record decision telemetry",
    "websearch.provider": "Web search provider",
    "web.iconTheme": "Icon theme (web)",
    "tui.paddingX": "Terminal horizontal padding",
    "tui.contentPaddingX": "Terminal content padding",
    "tui.skillSlashCommands": "Skills as slash commands (terminal)",
    "agents.active": "Active agent",
    "agents.effort": "Agent reasoning effort",
    "analysis.enabled": "Data analysis",
    "analysis.smartDashboard": "Smart Dashboard (dashboard_generate)",
    "analysis.limits.timeoutMs": "Analysis run timeout (ms)",
    "analysis.retention.jobsDays": "Keep analysis jobs (days)",
    "analysis.retention.intermediateDays": "Keep intermediate files (days)",
    "analysis.retention.artifactsDays": "Keep artifacts (days)",
    "tasks.enabled": "Background tasks",
    "tasks.maxPerSession": "Live background tasks per session",
    "tasks.maxRunMs": "Background task time limit (ms)",
    "tasks.maxOutputBytes": "Background task log size (bytes)",
    "tasks.retentionDays": "Keep finished tasks (days)",
    "goal.enabled": "Session goals (/goal)",
    "goal.maxTurns": "Goal turn limit",
    "goal.maxMinutes": "Goal time limit (minutes)",
    "goal.repeatedReplyLimit": "Pause a goal after identical replies",
    "goal.noToolTurnsLimit": "Pause a goal after turns without tools",
    "goal.blockedRepeats": "Turns the agent must report a blocker",
    "plan.diagrams": "Plan diagrams",
    "plan.maxDiagrams": "Most diagrams per plan",
  },
  es: {
    "compaction.auto": "Compactar el contexto automáticamente",
    "compaction.threshold": "Umbral de compactación (fracción de la ventana)",
    "compaction.keepTurns": "Turnos recientes conservados literalmente",
    "compaction.maxOutputTokens": "Longitud del resumen (tokens)",
    "context.claudeMdFallback": "Leer CLAUDE.md si no hay AGENTS.md",
    "context.maxBytes": "Límite de instrucciones del proyecto (bytes)",
    "limits.maxTurns": "Turnos por run",
    "limits.maxOutputTokens": "Tokens de salida por turno",
    "limits.maxContextChars": "Caracteres de contexto enviados",
    "limits.timeoutMs": "Límite de tiempo de la ejecución, tiempo activo (ms)",
    "limits.firstTokenTimeoutMs": "Tiempo máximo al primer token (ms)",
    "limits.firstTokenRetries": "Reintentos cuando el modelo no responde",
    "limits.truncationRecoveries": "Recuperaciones de salida truncada",
    "pluginHooks.timeoutMs": "Tiempo máximo de hooks de plugins (ms)",
    "pluginHooks.disposeTimeoutMs": "Tiempo máximo de cierre de plugins (ms)",
    "decisions.enabled": "Decision Intelligence",
    "decisions.provider": "Proveedor de decisiones",
    "decisions.timeoutMs": "Tiempo máximo de decisión (ms)",
    "decisions.minConfidence": "Confianza mínima de las decisiones",
    "decisions.telemetry": "Registrar telemetría de decisiones",
    "websearch.provider": "Proveedor de búsqueda web",
    "web.iconTheme": "Tema de iconos (web)",
    "tui.paddingX": "Margen horizontal del terminal",
    "tui.contentPaddingX": "Margen del contenido del terminal",
    "tui.skillSlashCommands": "Skills como comandos slash (terminal)",
    "agents.active": "Agente activo",
    "agents.effort": "Esfuerzo de razonamiento del agente",
    "analysis.enabled": "Análisis de datos",
    "analysis.smartDashboard": "Smart Dashboard (dashboard_generate)",
    "analysis.limits.timeoutMs": "Tiempo máximo de una ejecución de análisis (ms)",
    "analysis.retention.jobsDays": "Conservar trabajos de análisis (días)",
    "analysis.retention.intermediateDays": "Conservar archivos intermedios (días)",
    "analysis.retention.artifactsDays": "Conservar artefactos (días)",
    "tasks.enabled": "Tareas en segundo plano",
    "tasks.maxPerSession": "Tareas en segundo plano activas por sesión",
    "tasks.maxRunMs": "Tiempo máximo de una tarea en segundo plano (ms)",
    "tasks.maxOutputBytes": "Tamaño del registro de una tarea (bytes)",
    "tasks.retentionDays": "Conservar tareas terminadas (días)",
    "goal.enabled": "Objetivos de sesión (/goal)",
    "goal.maxTurns": "Límite de turnos de un objetivo",
    "goal.maxMinutes": "Límite de tiempo de un objetivo (minutos)",
    "goal.repeatedReplyLimit": "Pausar un objetivo tras respuestas idénticas",
    "goal.noToolTurnsLimit": "Pausar un objetivo tras turnos sin herramientas",
    "goal.blockedRepeats": "Turnos en que el agente debe reportar un bloqueo",
    "plan.diagrams": "Diagramas del plan",
    "plan.maxDiagrams": "Máximo de diagramas por plan",
  },
};

/** The label of a settable key in `locale`; an unknown key shows its own name, never throws. */
export const settingLabel = (key: string, locale: Locale): string =>
  SETTING_LABELS[locale][key] ?? SETTING_LABELS.en[key] ?? key;
