/**
 * Regenerates `packages/core/src/analysis/data/engine-source.ts`: the data engine (ingestion and
 * read-only queries on `node:sqlite`) bundled into one ES module script that the host writes to
 * disk and runs in a child process. A bundle is embedded for the same reason as the Python
 * runtime: the npm package and the Bun binary ship JavaScript only, and a child process cannot
 * import files that live inside a compiled binary. Uses `bun build` (a dev dependency).
 * Usage: node --experimental-strip-types scripts/analysis-data-engine.ts
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { ENGINE_DIR, engineInputsHash } from "./analysis-data-engine-inputs.ts";

const root = resolve(import.meta.dirname ?? ".", "..");
const target = join(root, ENGINE_DIR, "engine-source.ts");
const work = mkdtempSync(join(tmpdir(), "alisio-engine-"));
try {
  const out = join(work, "engine.mjs");
  execFileSync(
    resolve(root, "node_modules/.bin/bun"),
    [
      "build",
      join(root, ENGINE_DIR, "engine-entry.ts"),
      "--target",
      "node",
      "--format",
      "esm",
      "--outfile",
      out,
    ],
    { stdio: "inherit" },
  );
  const code = readFileSync(out, "utf8");
  writeFileSync(
    target,
    `// Generated by scripts/analysis-data-engine.ts from the modules listed in
// scripts/analysis-data-engine-inputs.ts. Do not edit.
/** Hash of the engine inputs this bundle was built from. */
export const ENGINE_INPUT_SHA256 = ${JSON.stringify(engineInputsHash(root))};
/** The data engine as one ES module script (run with node, bun or the compiled binary). */
export const ENGINE_SOURCE: string = ${JSON.stringify(code)};
`,
  );
  execFileSync(resolve(root, "node_modules/.bin/biome"), ["format", "--write", target], {
    stdio: "inherit",
  });
} finally {
  rmSync(work, { recursive: true, force: true });
}
