/**
 * Regenerates `packages/core/src/analysis/python/sources.ts` from the `alisio_runtime/*.py`
 * sources next to it (plus the vendored Chart.js bundle `chart.umd.min.js`, its license and the
 * shared `charts.css`, `charts-boot.js` and `html-base.css` assets), then formats it with Biome.
 * The Python files are the source of truth; the generated module carries them into the npm
 * package and the standalone binary (both ship JavaScript only).
 * `tests/analysis-runtime-sources.test.ts` fails when the two drift apart.
 * Usage: node --experimental-strip-types scripts/analysis-runtime-sources.ts
 */
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const dir = resolve("packages/core/src/analysis/python");
const sourceDir = join(dir, "alisio_runtime");
const target = join(dir, "sources.ts");

const files = readdirSync(sourceDir)
  .filter((name) => /\.(py|js|txt|css)$/.test(name))
  .sort();
const entries = files
  .map(
    (name) =>
      `  ${JSON.stringify(name)}: ${JSON.stringify(readFileSync(join(sourceDir, name), "utf8"))},`,
  )
  .join("\n");
writeFileSync(
  target,
  `// Generated by scripts/analysis-runtime-sources.ts from alisio_runtime/*.{py,js,txt,css}. Do not edit.
/** The pure-Python \`alisio_runtime\` package copied next to every python_run script. */
export const ALISIO_RUNTIME_FILES: Record<string, string> = {
${entries}
};
`,
);
execFileSync(resolve("node_modules/.bin/biome"), ["format", "--write", target], {
  stdio: "inherit",
});
