/**
 * Regenerates `packages/core/src/changelog/data.ts` from the root `CHANGELOG.md`, then formats it
 * with Biome. `CHANGELOG.md` is the source of truth; the generated module carries the parsed
 * entries into the npm package and the standalone binary (both ship JavaScript only, and
 * `pack-check` allows no `.json` under `dist`), so `/changelog` works offline.
 * `tests/changelog.test.ts` fails when the two drift apart.
 *
 * Usage: node --experimental-strip-types scripts/changelog-data.ts
 */
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { parseChangelog } from "../packages/core/src/changelog/parse.ts";

const source = resolve("CHANGELOG.md");
const target = resolve("packages/core/src/changelog/data.ts");

const entries = existsSync(source) ? parseChangelog(readFileSync(source, "utf8")) : [];
const content = `// Generated by scripts/changelog-data.ts from CHANGELOG.md. Do not edit.
import type { ChangelogEntry } from "@alisio/sdk";

/** The parsed \`CHANGELOG.md\` shipped with the package (newest entry first). */
export const CHANGELOG_DATA: { schema: 1; entries: ChangelogEntry[] } = ${JSON.stringify(
  { schema: 1, entries },
  null,
  2,
)};
`;

writeFileSync(target, content);
execFileSync(resolve("node_modules/.bin/biome"), ["format", "--write", target], {
  stdio: "inherit",
});
