// Generated by scripts/changelog-data.ts from CHANGELOG.md. Do not edit.
import type { ChangelogEntry } from "@alisio/sdk";

/** The parsed `CHANGELOG.md` shipped with the package (newest entry first). */
export const CHANGELOG_DATA: { schema: 1; entries: ChangelogEntry[] } = {
  schema: 1,
  entries: [
    {
      version: "0.4.0",
      date: "2026-10-03",
      sections: [
        {
          title: "Added",
          items: [
            "Smart Dashboard: ask for a dashboard of a dataset and `dashboard_generate` builds it from ready-made components (KPIs, trend, ranking, composition, correlation, table) with no generated code. The numbers come from read-only queries on the dataset, the result is validated before it is drawn, and asking again with another goal regenerates it. It follows the columns your request names.",
            "An optional decision provider can refine the dashboard's purpose; without one the rules decide.",
            "The `analysis.smartDashboard` setting (on by default) turns the tool and its guidance off.",
            "Live progress for running tools in the terminal and in the collapsed web transcript row.",
          ],
        },
        {
          title: "Improved",
          items: [
            "Dashboard KPIs use compact numbers (the full value is kept for tooltips and screen readers) and readable column names.",
          ],
        },
        {
          title: "Fixed",
          items: [
            '`alisio run "/plugin.id:name"` runs the plugin command instead of sending it to the model, and the web command palette lists plugin commands without typing a prefix.',
            "Horizontal bar charts show the tooltip of the hovered row, in Python and Smart Dashboard dashboards.",
          ],
        },
      ],
    },
    {
      version: "0.3.0",
      date: "2026-10-03",
      sections: [
        {
          title: "Added",
          items: [
            "Decision Intelligence: an optional provider contract that lets a plugin answer small, closed decisions (pick an option, yes/no, a level) without a full model generation. Alisio works the same without a provider; installing a provider plugin does not activate it.",
            "`/decisions` (terminal and web) shows whether decisions are enabled, the active provider, its health and the session metrics. `/stats` gains a Decision Intelligence section once a decision has run.",
            "New settings: the `decisions` block (`enabled`, `provider`, `timeoutMs`, `minConfidence`, `telemetry`), plugin options in `pluginOverrides.<id>.options` and `pluginHooks.disposeTimeoutMs`.",
          ],
        },
        {
          title: "Improved",
          items: [
            "Plugins are shut down in parallel, each with its own time limit, so one slow plugin no longer delays the others.",
            "`alisio run` now shuts plugins down cleanly on SIGTERM and SIGHUP, not only on Ctrl+C.",
          ],
        },
      ],
    },
    {
      version: "0.2.1",
      date: "2026-10-02",
      sections: [
        {
          title: "Fixed",
          items: [
            'A run no longer stops with "reached its 600 s limit" while you read a plan or answer a question. The run time limit (`limits.timeoutMs`) now counts only active time: the time the agent waits for you (the plan review, a question, a tool approval) is not counted. A model or tool that really stalls still hits the limit. The same applies to the `goal.maxMinutes` cap of a session goal.',
            'A run that ended or was stopped during a plan review no longer leaves the next message failing with an "Uncertain tool outcome" error.',
            "In the web, a plan review or a question can wait up to 60 minutes for your answer (tool approvals still expire after 10 minutes).",
            'The Settings label of `limits.timeoutMs` said "Provider request timeout"; it now says it is the run time limit.',
          ],
        },
      ],
    },
    {
      version: "0.2.0",
      date: "2026-10-02",
      sections: [
        {
          title: "Added",
          items: [
            "Plan diagrams: the plan agent can attach small Mermaid diagrams (flows, sequences, architecture) to the plan it proposes with `exit_plan`.",
            "A plan viewer in the web UI: the plan opens in the artifact panel with its diagrams drawn in your theme, next to the plan review. The terminal shows the diagram source.",
            "Plan files are saved in a plan folder with a `plan.json` manifest, so the plan and its diagrams are easy to find and reuse.",
            "Two new settings, `plan.diagrams` and `plan.maxDiagrams` (in the configuration file, **Settings** in the web and `/settings` in the terminal), to turn diagrams off or cap how many a plan keeps.",
            "Dashboard charts for Python analysis: `alisio_runtime.charts` builds interactive pie, donut, bar, line, area and scatter charts, KPI tiles and cards with an embedded Chart.js (MIT), so dashboards work offline, in the viewer and in the downloaded file.",
          ],
        },
        {
          title: "Improved",
          items: [
            "Charts adapt to their card and follow the light and dark theme, with value labels, tooltips and a data table for screen readers.",
            "The pure-SVG helpers (`alisio_runtime.svg`) were rewritten: they scale with their container and carry a title and description.",
            "The agent receives clearer guidance for `python_run` about how to draw charts and dashboards.",
          ],
        },
        {
          title: "Fixed",
          items: [
            "Pie charts drew wrong or broken slices in generated dashboards (including a single 100% slice), and bar charts rendered at a fixed small size.",
            "A dashboard that draws SVG pies by hand, uses fixed-size SVG charts or loads a script from the network now gets a warning in the `python_run` result that points to the chart helpers.",
          ],
        },
      ],
    },
    {
      version: "0.1.1",
      date: "2026-10-02",
      sections: [
        {
          title: "Fixed",
          items: [
            "The web UI no longer scrolls the page and leaves a blank gap under the interface while a reply is streaming: the app now always fills the window exactly and only its inner panels scroll.",
            "The Alisio version is shown in the web UI: **Settings → About** and, discreetly, the bottom of the sidebar.",
          ],
        },
      ],
    },
    {
      version: "0.1.0",
      date: "2026-10-02",
      sections: [
        {
          title: "Added",
          items: [
            "The terminal UI and `alisio serve`, a local web UI with several sessions and workspaces at once, streaming, approvals, themes and English/Spanish; both run the same agent core.",
            "Agents: define your own in `.agents/agents`, manage them with `/agents` (terminal and web) and switch with `/agent:<id>`; Shift+Tab cycles the main agents (build, plan and your own) in the terminal and the web composer.",
            "Plan mode with plan review: the agent proposes a plan with `exit_plan` and you approve or revise it before anything changes.",
            "`/permission` (also `/permissions`) switches between ask, auto and full-access modes, and saved permissions are reviewed and revoked from the same menu.",
            "Python analysis: the agent writes and runs a script and publishes its outputs as artifacts (dashboards, reports, charts, spreadsheets); `/artifacts` lists them and the web shows them in an artifact panel.",
            "Tabular datasets: attach CSV, TSV or XLSX files and the agent inspects and queries them; the web has a table viewer.",
            "Background tasks: long commands keep running while you work; `/tasks` lists, inspects and stops them.",
            "`/goal <objective>` keeps the agent working on one objective, turn after turn, with a token budget (`budget=50k`), turn and time limits, and breakers for repeated replies; it never runs in plan mode and waits for approvals, questions and background tasks.",
            "`/reload` reloads the configuration, agents, skills, prompt templates and MCP servers between turns; a broken configuration leaves your session untouched.",
            "`/changelog [version]` shows what changed in each release, and Alisio mentions the news once after an upgrade.",
            "A Memory tab in the web UI and plugin-provided data views.",
            "`/btw` asks a side question about the session without adding it to the conversation.",
            "Approved access to directories outside the workspace (`--add-dir`, or an approval per directory).",
          ],
        },
        {
          title: "Improved",
          items: [
            "Live run progress in the terminal and the web: what the run is doing, how long it has been quiet and the last activity.",
            "A request that stays silent until the first-token limit is retried once and then ends with a readable error.",
            "The output limit of each request comes from the maximum the model declares in its catalog, when the provider reports it.",
            "Rich renderers for code, diffs, terminal output, JSON, test results, Mermaid diagrams and formulas.",
          ],
        },
        {
          title: "Fixed",
          items: [
            "A model reply that is cut off at the output limit is continued automatically instead of failing the turn.",
            "Project plugins, skills and MCP servers are merged with your global configuration instead of replacing it.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.28",
      date: "2026-10-01",
      sections: [
        {
          title: "Added",
          items: [
            "A model reply that is cut off at the output limit is continued automatically instead of failing the turn.",
            "A model request that stays silent until the first-token limit is retried once before it fails.",
          ],
        },
        {
          title: "Changed",
          items: [
            "The output limit of each request now comes from the maximum the model declares, when the provider reports it.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.27",
      date: "2026-10-01",
      sections: [
        {
          title: "Added",
          items: [
            "Live run progress in the terminal and the web: what the run is doing, how long it has been quiet and the last activity.",
          ],
        },
        {
          title: "Changed",
          items: [
            "A silent model request now ends with a readable error, and the timeout defaults were adjusted.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.26",
      date: "2026-10-01",
      sections: [
        {
          title: "Added",
          items: [
            "Python analysis: the agent can write and run a script and publish its outputs as downloadable artifacts (dashboards, reports, charts, spreadsheets).",
            "`/artifacts` lists and opens a session's artifacts; the web shows them as cards with a side panel.",
            "`/permissions` reviews and revokes the permissions you saved for a session.",
            "Tabular data in the web: attach CSV, TSV or XLSX files and the agent inspects and queries them.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.25",
      date: "2026-09-30",
      sections: [
        {
          title: "Changed",
          items: [
            "The Agents window of the web UI can be maximized and keeps its scrollbar inside the corners.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.24",
      date: "2026-09-30",
      sections: [
        {
          title: "Added",
          items: [
            "Manage agents without leaving Alisio: `/agents` creates, edits and deletes agent files from templates, in the terminal and in the web Agents window.",
            "`/agent:<id>` activates an agent from the slash menu.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.23",
      date: "2026-09-30",
      sections: [
        {
          title: "Changed",
          items: [
            "Refreshed branding across the terminal and the web, with an About page in the web settings.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.22",
      date: "2026-09-30",
      sections: [
        {
          title: "Added",
          items: [
            "`/btw` asks a side question about the session without adding it to the conversation, in the terminal and in the web.",
            "Archive workspaces in the web sidebar and pick a folder with the native folder dialog.",
            "A redesigned stop control in the web composer and the official logo and favicon.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.21",
      date: "2026-09-30",
      sections: [
        {
          title: "Added",
          items: [
            "`alisio serve` starts a local web UI with several sessions and workspaces at once, streaming, approvals, themes and English/Spanish.",
            "Rich renderers for code, diffs, terminal output, JSON, test results, Mermaid diagrams and formulas, plus a files panel and a trajectory tab.",
            "Image attachments in the web composer.",
            "Manage plugins, skills, MCP servers, agent presets, providers and models from the web settings.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.20",
      date: "2026-09-30",
      sections: [
        {
          title: "Added",
          items: [
            "Approved access to directories outside the workspace (`--add-dir`, or an approval per directory).",
            "A configurable inset for the transcript in the terminal (`/settings`).",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.19",
      date: "2026-09-29",
      sections: [
        {
          title: "Changed",
          items: [
            "External provider plugins moved to the separate alisio-plugins repository; `@alisio/plugin-openai-compatible` stays built in.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.18",
      date: "2026-09-28",
      sections: [
        {
          title: "Fixed",
          items: [
            "Project plugins, skills and MCP servers are merged with your global configuration instead of replacing it.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.17",
      date: "2026-09-28",
      sections: [
        {
          title: "Added",
          items: ["Plugins declare categories, and the plugin picker groups them under headers."],
        },
      ],
    },
    {
      version: "0.1.0-alpha.16",
      date: "2026-09-27",
      sections: [
        {
          title: "Added",
          items: [
            "Rich MCP results, syntax highlighting in Markdown and clearer presentation of tool calls.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.15",
      date: "2026-09-27",
      sections: [
        {
          title: "Added",
          items: [
            "Active agents: `/agents` switches the main agent, and `/effort` sets the reasoning effort.",
            "The status line below the editor shows the agent, model, provider and effort.",
          ],
        },
      ],
    },
    {
      version: "0.1.0-alpha.14",
      date: "2026-09-27",
      sections: [
        {
          title: "Added",
          items: ["A DuckDuckGo web search provider that needs no API key."],
        },
      ],
    },
    {
      version: "0.1.0-alpha.13",
      date: "2026-09-26",
      sections: [
        {
          title: "Added",
          items: [
            "A soft turn limit that lets the agent finish gracefully, and richer package READMEs.",
          ],
        },
        {
          title: "Changed",
          items: ["The header shows the model, provider and workspace identity."],
        },
      ],
    },
    {
      version: "0.1.0-alpha.12",
      date: "2026-09-26",
      sections: [
        {
          title: "Fixed",
          items: [
            "Output-budget defaults, a cap on the context sent to the model and faster exit.",
          ],
        },
        {
          title: "Added",
          items: ["The header shows the Git branch of the workspace."],
        },
      ],
    },
    {
      version: "0.1.0-alpha.1",
      date: "2026-09-25",
      sections: [
        {
          title: "Added",
          items: [
            "Terminal UI for any OpenAI-compatible endpoint, with permissioned local tools, context compaction and persistent memory.",
            "Subagents, `ask_user_question`, web tools, per-directory project trust and pasting text or images into the editor.",
            "Providers, MCP servers and skills managers, `/settings`, slash completion for skills and an npm plugin installer.",
            "A context bar that follows the model's real window, with per-profile overrides for local servers.",
          ],
        },
      ],
    },
  ],
};
